### ISSUE TITLE
Is `angular-blocks` compatible with `ui.router` ?

### ISSUE THREAD

**Issue by aronysidoro** [wmluke/angular-blocks#13]
I wanted to know if `angular-blocks` compatible with `angular-ui-router` ?

I had tried to get them to work together, but didn't have any luck so far. I've only been using Angular for 2 months, sorry if this is a simple question that I just couldn't figure out.

Thank you

**Comment by wmluke** [comment]
Hi @aronysidoro,

It looks like you found your answer, but just for future reference...

You can use `angular-blocks` with `angular-ui-router`, but before going that route I recommend looking at https://github.com/angular-ui/ui-router/wiki/Multiple-Named-Views.  Theoretically, you should be able to use multiple `ui-view`s within a single `angular-blocks` layout, but practically speaking I have not seen this done.

Good Luck!
Luke

**Comment by aronysidoro** [comment]
Luke,

Thank you. The link you posted is actually what I ended up using for the time being.  Lesson learned, it's better to read a libraries wiki before jumping on google.  Thanks!
